#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/cscpassist/cscpassist /usr/bin/cscpassist
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/cscpassist.service ]; then
			rm /etc/systemd/system/cscpassist.service /usr/lib/systemd/system/cscpassist.service /usr/lib/systemd/user/cscpassist.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/cscpassist/files/systemd/cscpassist.service /usr/lib/systemd/system/cscpassist.service
		systemctl daemon-reload
		systemctl enable cscpassist
		systemctl start cscpassist
	fi
fi
